# Uni-Date服务器配置文件
# 本文件包含服务器运行所需的所有配置参数

# 服务器基本设置
server:
  port: 8080                # 服务器监听端口，可根据需要修改
  mode: debug               # 运行模式：debug(调试模式，提供详细日志)、release(生产模式，优化性能)、test(测试模式)
  # host: localhost         # 可选：指定服务器主机名，默认为localhost

# 数据库连接配置
database:
  driver: postgres          # 数据库类型：目前支持postgres(PostgreSQL)
  host: localhost           # 数据库服务器地址
  port: 5432                # PostgreSQL默认端口
  username: postgres        # 数据库用户名
  password: password        # 数据库密码（生产环境建议使用环境变量或密钥管理系统）
  name: uni_date            # 数据库名称
  sslmode: disable          # SSL连接模式：disable(禁用)、require(必需)、verify-ca(验证CA)、verify-full(完全验证)
  # max_open_conns: 10      # 可选：最大打开连接数
  # max_idle_conns: 5       # 可选：最大空闲连接数

# Redis缓存配置
# 用于存储会话、临时数据和实现分布式锁等功能
redis:
  host: localhost           # Redis服务器地址
  port: 6379                # Redis默认端口
  password:                 # Redis密码，如无密码则留空
  db: 0                     # 使用的数据库索引，默认为0
  # pool_size: 10           # 可选：连接池大小
  # min_idle_conns: 5       # 可选：最小空闲连接数

# JWT认证配置
# 用于生成和验证用户身份令牌
jwt:
  secret: your_jwt_secret_key  # JWT签名密钥（生产环境必须更改为强密钥并妥善保管）
  expiration: 24h              # 令牌有效期，格式：数字+单位(s秒,m分钟,h小时)
  # refresh_expiration: 168h   # 可选：刷新令牌有效期，默认为7天

# CORS跨域资源共享配置
# 控制哪些域名可以访问API
cors:
  allowed_origins:          # 允许访问API的源域名列表
    - http://localhost:3000 # 前端开发服务器地址
    # - https://yourdomain.com # 生产环境域名
  allowed_methods:          # 允许的HTTP请求方法
    - GET                   # 获取资源
    - POST                  # 创建资源
    - PUT                   # 更新资源
    - DELETE                # 删除资源
    - OPTIONS               # 预检请求
  # allowed_headers:        # 可选：允许的HTTP请求头
  #   - Content-Type
  #   - Authorization
  # exposed_headers:        # 可选：允许客户端访问的响应头
  #   - Content-Length
  # allow_credentials: true # 可选：是否允许携带凭证(cookies)

# 日志配置
# log:
#   level: info             # 日志级别：debug, info, warn, error
#   format: json            # 日志格式：json, text
#   output: stdout          # 输出位置：stdout, file
#   file_path: logs/app.log # 当output为file时的文件路径

# 文件上传配置
# upload:
#   max_size: 5             # 最大文件大小(MB)
#   allowed_types:          # 允许的文件类型
#     - image/jpeg
#     - image/png
#   storage_path: uploads/  # 存储路径