# Server configuration: controls how your backend runs.
server:
  port: "8080"
  mode: debug        # The running mode: 'debug' for development, 'release' for production, 'test' for testing.
  readTimeout: 10s
  writeTimeout: 10s

# Database configuration: tells your backend how to connect to your PostgreSQL database.
database:
  driver: postgres   # The type of database. Here, it's PostgreSQL.
  host: "localhost"    # The address of your database server. 'localhost' means your own computer.
  port: "5432"         # The default port for PostgreSQL.
  user: "ken"       # Your database username.
  password: ""
  dbname: "uni-date" # The name of your database.
  sslmode: "disable"   # SSL mode for the database connection. 'disable' is fine for local development.

# Redis configuration: settings for connecting to your Redis cache.
redis:
  host: localhost    # Redis server address.
  port: 6379         # Default Redis port.
  password:          # Redis password. Leave blank for development.
  db: 0              # Redis database number. 0 is the default.

# JWT configuration: controls how user login tokens are created and validated.
jwt:
  secret: "uni-date-app-secret-key-change-in-production"
  expiresIn: 168h # 7天

# CORS configuration: controls which frontend addresses can access your backend API.
cors:
  allowed_origins:
    - http://localhost:3000   # Allow requests from your frontend dev server (React runs on 3000 by default).
  allowed_methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS